Repository dexterpuru/leetcode_java, pull requests merged in 2020-10, with the labels that each got.

#12 Added solution to find all anagrams in a string
  String/Find All Anagrams in a String/README.md
  String/Find All Anagrams in a String/Solution.java
  String/Longest Palindromic Substring/README.md
  String/Longest Palindromic Substring/leetcode.txt
  String/Longest Palindromic Substring/problem.txt
Labels: Hacktoberfest

#17 Added solution and README.md for 'Add Two Numbers II' problem
  Linked List/Add Two Numbers II/README.md
  Linked List/Add Two Numbers II/Solution.java
  Linked List/Add Two Numbers/README.md
  list_of_questions.txt
Labels: Hacktoberfest

#33 Solution for Sub-array product less than k issue #22
  Array/SubarrayProductLessThanK/README.md
  Array/SubarrayProductLessThanK/Solution.java
  list_of_questions.txt
Labels: Hacktoberfest

#32 [issue #21] number of recent calls
  Queue/Number of Recent Calls/README.md
  Queue/Number of Recent Calls/Solution.java
  list_of_questions.txt
Labels: Hacktoberfest

#35 Course Schedule
  Graph/Course Schedule/README.md
  Graph/Course Schedule/Solution.java
  list_of_questions.txt
Labels: Hacktoberfest

#29 added evaluate division
  Graph/EvaluateDivision.java
Labels: Hacktoberfest

#34 [issue #23] evaluate division
  Graph/EvaluateDivision/README.md
  Graph/EvaluateDivision/Solution.java
  list_of_questions.txt
Labels: Hacktoberfest

#45 Best time to buy and sell stock
  Array/BestTimeToBuyAndSellStock/README.md
  Array/BestTimeToBuyAndSellStock/Solution.java
  list_of_questions.txt
Labels: Hacktoberfest, hacktoberfest-accepted

#50 Power of two
  Math/README.md
  Math/Solution.java
  list_of_questions.txt
Labels: hacktoberfest-accepted

#52 adding solution for max depth of n-ary tree
  Graph/Maximum Depth of N-ary Tree/README.md
  Graph/Maximum Depth of N-ary Tree/Solution.java
  list_of_questions.txt
Labels: Hacktoberfest, hacktoberfest-accepted

#61 Added Jump Game
  Array/Jump Game/README.md
  Array/Jump Game/Solution.java
  list_of_questions.txt
Labels: Hacktoberfest, hacktoberfest-accepted

#69 Added description and solution for problem Friends of Appropriate Ages
  Algorithms/Friends Of Appropriate Ages/README.md
  Algorithms/Friends Of Appropriate Ages/Solution.java
  problemStatementList.md
Labels: Hacktoberfest, hacktoberfest-accepted

#74 Boats to save people
  Algorithms/Boats to Save People/README.md
  Algorithms/Boats to Save People/Solution.java
  problemStatementList.md
Labels: Hacktoberfest, hacktoberfest-accepted

#76 Find and replace pattern
  String/Find and Replace Pattern/README.md
  String/Find and Replace Pattern/Solution.java
  problemStatementList.md
Labels: Hacktoberfest, hacktoberfest-accepted
